//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComandaEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int Id { get; set; }
        public Nullable<decimal> Perc_Desconto { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public Nullable<decimal> Perc_Acrescimo { get; set; }
        public Nullable<decimal> Acrescimo { get; set; }
    }
}
