//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComandaEletronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.PedidoItem = new HashSet<PedidoItem>();
        }
    
        public int Id { get; set; }
        public int Id_Cliente { get; set; }
        public int Id_Comanda { get; set; }
        public int Id_Atendente { get; set; }
        public int Id_Mesa { get; set; }
        public byte Pago { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Atendente Atendente { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Comanda Comanda { get; set; }
        public virtual Mesa Mesa { get; set; }
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
    }
}
